---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-storage-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/jira-storage/
