---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-storage-claim
  labels:
    type: jira-storage-local
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi